name: Build and Deploy FastAPI Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker image
        run: |
          docker build -t fastapi-lambda .

      - name: Tag image with full ECR path
        run: |
          docker tag fastapi-python-lambda:latest 539247476671.dkr.ecr.us-east-1.amazonaws.com/fastapi-python-lambda:latest

      - name: Push Docker image to ECR
        run: |
          docker push 539247476671.dkr.ecr.us-east-1.amazonaws.com/fastapi-python-lambda:latest

      - name: Update Lambda function with new container image
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --image-uri 539247476671.dkr.ecr.us-east-1.amazonaws.com/fastapi-python-lambda:latest \
            --region ${{ secrets.AWS_REGION }}
